# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Mon Apr  6 19:43:09 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui, Qt
from PyQt4.Qwt5 import *

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1256, 531)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1241, 481))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.qwtPlot = QwtPlot(self.tab)
        self.qwtPlot.setGeometry(QtCore.QRect(340, 0, 571, 221))
        self.qwtPlot.setObjectName(_fromUtf8("qwtPlot"))
        self.frame = QtGui.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(0, 0, 161, 451))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 130, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(0, 16, 66, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.toolButton = QtGui.QToolButton(self.frame)
        self.toolButton.setGeometry(QtCore.QRect(0, 30, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.toolButton.setFont(font)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.listWidget = QtGui.QListWidget(self.frame)
        self.listWidget.setGeometry(QtCore.QRect(0, 145, 161, 141))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.frame_4 = QtGui.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(0, 300, 161, 21))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.pushButton = QtGui.QPushButton(self.frame_4)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_6 = QtGui.QPushButton(self.frame_4)
        self.pushButton_6.setGeometry(QtCore.QRect(80, 0, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.checkBox = QtGui.QCheckBox(self.frame)
        self.checkBox.setGeometry(QtCore.QRect(0, 285, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.checkBox_2 = QtGui.QCheckBox(self.frame)
        self.checkBox_2.setGeometry(QtCore.QRect(65, 286, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.listWidget_3 = QtGui.QListWidget(self.frame)
        self.listWidget_3.setGeometry(QtCore.QRect(0, 51, 161, 81))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.listWidget_3.setFont(font)
        self.listWidget_3.setObjectName(_fromUtf8("listWidget_3"))
        self.pushButton_7 = QtGui.QPushButton(self.frame)
        self.pushButton_7.setGeometry(QtCore.QRect(107, 12, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(0, 320, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.listWidget_7 = QtGui.QListWidget(self.frame)
        self.listWidget_7.setGeometry(QtCore.QRect(0, 335, 161, 91))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.listWidget_7.setFont(font)
        self.listWidget_7.setObjectName(_fromUtf8("listWidget_7"))
        self.pushButton_5 = QtGui.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(35, 425, 98, 21))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.frame_2 = QtGui.QFrame(self.tab)
        self.frame_2.setGeometry(QtCore.QRect(160, 80, 181, 371))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.listWidget_2 = QtGui.QListWidget(self.frame_2)
        self.listWidget_2.setGeometry(QtCore.QRect(0, 30, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.listWidget_2.setFont(font)
        self.listWidget_2.setObjectName(_fromUtf8("listWidget_2"))
        item = QtGui.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget_2.addItem(item)
        self.label_6 = QtGui.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(0, 15, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.toolButton_2 = QtGui.QToolButton(self.frame_2)
        self.toolButton_2.setGeometry(QtCore.QRect(50, 101, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.toolButton_2.setFont(font)
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.label_5 = QtGui.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(0, 90, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.pushButton_3 = QtGui.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(60, 345, 121, 26))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.label_9 = QtGui.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(0, 0, 106, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.listWidget_5 = QtGui.QListWidget(self.frame_2)
        self.listWidget_5.setGeometry(QtCore.QRect(0, 120, 181, 81))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.listWidget_5.setFont(font)
        self.listWidget_5.setObjectName(_fromUtf8("listWidget_5"))
        self.listWidget_6 = QtGui.QListWidget(self.frame_2)
        self.listWidget_6.setGeometry(QtCore.QRect(0, 215, 181, 111))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.listWidget_6.setFont(font)
        self.listWidget_6.setObjectName(_fromUtf8("listWidget_6"))
        self.label_20 = QtGui.QLabel(self.frame_2)
        self.label_20.setGeometry(QtCore.QRect(0, 200, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.pushButton_9 = QtGui.QPushButton(self.frame_2)
        self.pushButton_9.setGeometry(QtCore.QRect(0, 345, 51, 26))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.pushButton_10 = QtGui.QPushButton(self.frame_2)
        self.pushButton_10.setGeometry(QtCore.QRect(0, 100, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.frame_7 = QtGui.QFrame(self.frame_2)
        self.frame_7.setGeometry(QtCore.QRect(-1, 325, 181, 21))
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.radioButton = QtGui.QRadioButton(self.frame_7)
        self.radioButton.setGeometry(QtCore.QRect(0, 0, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.radioButton_2 = QtGui.QRadioButton(self.frame_7)
        self.radioButton_2.setGeometry(QtCore.QRect(90, 0, 86, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.label_17 = QtGui.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(910, 0, 321, 221))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(910, 230, 331, 211))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(650, 225, 266, 221))
        self.label_7.setText(_fromUtf8(""))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.frame_5 = QtGui.QFrame(self.tab)
        self.frame_5.setGeometry(QtCore.QRect(160, 0, 181, 81))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.label_15 = QtGui.QLabel(self.frame_5)
        self.label_15.setGeometry(QtCore.QRect(40, 0, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.frame_5)
        self.label_16.setGeometry(QtCore.QRect(0, 11, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_19 = QtGui.QLabel(self.frame_5)
        self.label_19.setGeometry(QtCore.QRect(0, 41, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.spinBox = QtGui.QSpinBox(self.frame_5)
        self.spinBox.setGeometry(QtCore.QRect(40, 26, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox.setFont(font)
        self.spinBox.setMaximum(9999)
        self.spinBox.setProperty("value", 20)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.spinBox_2 = QtGui.QSpinBox(self.frame_5)
        self.spinBox_2.setGeometry(QtCore.QRect(40, 57, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setProperty("value", 7)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.plainTextEdit_2 = QtGui.QPlainTextEdit(self.tab)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(345, 225, 301, 221))
        self.plainTextEdit_2.setObjectName(_fromUtf8("plainTextEdit_2"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.frame_3 = QtGui.QFrame(self.tab_2)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 201, 451))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.listWidget_4 = QtGui.QListWidget(self.frame_3)
        self.listWidget_4.setGeometry(QtCore.QRect(10, 70, 181, 101))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.listWidget_4.setFont(font)
        self.listWidget_4.setObjectName(_fromUtf8("listWidget_4"))
        self.label_12 = QtGui.QLabel(self.frame_3)
        self.label_12.setGeometry(QtCore.QRect(10, 55, 66, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.frame_3)
        self.label_13.setGeometry(QtCore.QRect(10, 375, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.pushButton_2 = QtGui.QPushButton(self.frame_3)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 6, 181, 26))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.frame_6 = QtGui.QFrame(self.frame_3)
        self.frame_6.setGeometry(QtCore.QRect(10, 260, 181, 96))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.toolButton_3 = QtGui.QToolButton(self.frame_6)
        self.toolButton_3.setGeometry(QtCore.QRect(50, 15, 131, 21))
        self.toolButton_3.setObjectName(_fromUtf8("toolButton_3"))
        self.label_10 = QtGui.QLabel(self.frame_6)
        self.label_10.setGeometry(QtCore.QRect(50, 0, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.frame_6)
        self.label_11.setGeometry(QtCore.QRect(0, 0, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.spinBox_3 = QtGui.QSpinBox(self.frame_6)
        self.spinBox_3.setGeometry(QtCore.QRect(0, 15, 46, 21))
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.listWidget_9 = QtGui.QListWidget(self.frame_6)
        self.listWidget_9.setGeometry(QtCore.QRect(0, 35, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.listWidget_9.setFont(font)
        self.listWidget_9.setObjectName(_fromUtf8("listWidget_9"))
        self.label_4 = QtGui.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(10, 35, 76, 17))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.comboBox = QtGui.QComboBox(self.frame_3)
        self.comboBox.setGeometry(QtCore.QRect(85, 35, 106, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.listWidget_8 = QtGui.QListWidget(self.frame_3)
        self.listWidget_8.setGeometry(QtCore.QRect(10, 195, 181, 66))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.listWidget_8.setFont(font)
        self.listWidget_8.setObjectName(_fromUtf8("listWidget_8"))
        self.pushButton_11 = QtGui.QPushButton(self.frame_3)
        self.pushButton_11.setGeometry(QtCore.QRect(10, 170, 76, 26))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.plainTextEdit = QtGui.QPlainTextEdit(self.frame_3)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 390, 181, 56))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.pushButton_4 = QtGui.QPushButton(self.frame_3)
        self.pushButton_4.setEnabled(True)
        self.pushButton_4.setGeometry(QtCore.QRect(105, 360, 81, 26))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.checkBox_3 = QtGui.QCheckBox(self.frame_3)
        self.checkBox_3.setGeometry(QtCore.QRect(85, 175, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.spinBox_4 = QtGui.QSpinBox(self.frame_3)
        self.spinBox_4.setGeometry(QtCore.QRect(150, 170, 41, 26))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_4.setFont(font)
        self.spinBox_4.setProperty("value", 1)
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.label_22 = QtGui.QLabel(self.tab_2)
        self.label_22.setGeometry(QtCore.QRect(200, 0, 711, 441))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1256, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Algorithms", None))
        self.label_2.setText(_translate("MainWindow", "Video file", None))
        self.toolButton.setText(_translate("MainWindow", "...", None))
        self.label_8.setText(_translate("MainWindow", "Environment analysis", None))
        self.pushButton.setText(_translate("MainWindow", "Run analysis", None))
        self.pushButton_6.setText(_translate("MainWindow", "Add to training", None))
        self.checkBox.setText(_translate("MainWindow", "Run all", None))
        self.checkBox_2.setText(_translate("MainWindow", "Raw preview", None))
        self.pushButton_7.setText(_translate("MainWindow", "Clear", None))
        self.label_3.setText(_translate("MainWindow", "Results", None))
        self.pushButton_5.setText(_translate("MainWindow", "Save results", None))
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("MainWindow", "indoor", None))
        item = self.listWidget_2.item(1)
        item.setText(_translate("MainWindow", "outdoor", None))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        self.label_6.setText(_translate("MainWindow", "Environment", None))
        self.toolButton_2.setText(_translate("MainWindow", "...", None))
        self.label_5.setText(_translate("MainWindow", "Add training sample:", None))
        self.pushButton_3.setText(_translate("MainWindow", "Generate training data", None))
        self.label_9.setText(_translate("MainWindow", "Classifier training", None))
        self.label_20.setText(_translate("MainWindow", "Algorithms for generating data to train:", None))
        self.pushButton_9.setText(_translate("MainWindow", "Clear", None))
        self.pushButton_10.setText(_translate("MainWindow", "Clear", None))
        self.radioButton.setText(_translate("MainWindow", "As text", None))
        self.radioButton_2.setText(_translate("MainWindow", "As binary", None))
        self.label_17.setText(_translate("MainWindow", "Original", None))
        self.label_18.setText(_translate("MainWindow", "Transformed", None))
        self.label_15.setText(_translate("MainWindow", "Analysis options", None))
        self.label_16.setText(_translate("MainWindow", "Period [frames]", None))
        self.label_19.setText(_translate("MainWindow", "Remove outliers [std.dev]", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Analysis", None))
        self.label_12.setText(_translate("MainWindow", "Classifier:", None))
        self.label_13.setText(_translate("MainWindow", "Efficiency:", None))
        self.pushButton_2.setText(_translate("MainWindow", "Load training data", None))
        self.toolButton_3.setText(_translate("MainWindow", "...", None))
        self.label_10.setText(_translate("MainWindow", "Sample:", None))
        self.label_11.setText(_translate("MainWindow", "Label:", None))
        self.label_4.setText(_translate("MainWindow", "Generated with:", None))
        self.pushButton_11.setText(_translate("MainWindow", "Add to testing", None))
        self.pushButton_4.setText(_translate("MainWindow", "Run test", None))
        self.checkBox_3.setText(_translate("MainWindow", "Param:", None))
        self.label_22.setText(_translate("MainWindow", "Preview", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Training &&Testing", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Other", None))
